# Dataset

In [31]:
# 외부 File을 Reading한 Data를 가정하기 위해, 임의의 np Data array 형성
# 1~5 열까지 x, 6열은 Y 라고 가정.

import numpy as np

nA=np.arange(6) + np.arange(0, 201, 10)[:, np.newaxis]
print(nA)

[[  0   1   2   3   4   5]
 [ 10  11  12  13  14  15]
 [ 20  21  22  23  24  25]
 [ 30  31  32  33  34  35]
 [ 40  41  42  43  44  45]
 [ 50  51  52  53  54  55]
 [ 60  61  62  63  64  65]
 [ 70  71  72  73  74  75]
 [ 80  81  82  83  84  85]
 [ 90  91  92  93  94  95]
 [100 101 102 103 104 105]
 [110 111 112 113 114 115]
 [120 121 122 123 124 125]
 [130 131 132 133 134 135]
 [140 141 142 143 144 145]
 [150 151 152 153 154 155]
 [160 161 162 163 164 165]
 [170 171 172 173 174 175]
 [180 181 182 183 184 185]
 [190 191 192 193 194 195]
 [200 201 202 203 204 205]]


# 1-1. Dataset by myself

In [36]:
import torch
from torch.autograd import Variable
from torch.utils.data import Dataset   # 1-2.와 import되는 함수가 다름

class MyDataset(Dataset):
    def __init__(self):
        # 입력된 Data를 x와 y set으로 분리
        self.x_data = Variable(torch.from_numpy(nA[:,0:-1]))
        self.y_data = Variable(torch.from_numpy(nA[:,[-1]]))
    
    def __len__(self):
        return len(self.x_data)
    
    def __getitem__(self, idx):
        x = self.x_data[idx]
        y = self.y_data[idx]
        return x, y

dataset = MyDataset()

# 1-2. Dataset in Torch

In [57]:
from torch.utils.data import TensorDataset   # 1-1과 import되는 함수가 다름

# 입력된 Data를 x와 y set으로 분리

x_data = Variable(torch.from_numpy(nA[:,0:-1]))
y_data = Variable(torch.from_numpy(nA[:,[-1]]))

dataset = TensorDataset(x_data, y_data)

* Dataset working 확인 (1-2, 1-2 공통)

In [53]:
# MyDataset 크기 확인
dataset.__len__()

21

In [54]:
# MyDataset i번째 원소 확인
i=1
dataset.__getitem__(i)

(tensor([10, 11, 12, 13, 14], dtype=torch.int32),
 tensor([15], dtype=torch.int32))

# DataLoader

In [56]:
from torch.utils.data import DataLoader

dataloader = DataLoader(dataset, batch_size = 3, shuffle=False)  #결과 확인을 쉽게 하기위해 shuffle 안함.

* DataLoader working 확인

In [55]:
for batch_idx, samples in enumerate(dataloader):
    x_train, y_train = samples
    print(x_train, y_train)
    print("batch %d finished" %batch_idx)

tensor([[ 0,  1,  2,  3,  4],
        [10, 11, 12, 13, 14],
        [20, 21, 22, 23, 24]], dtype=torch.int32) tensor([[ 5],
        [15],
        [25]], dtype=torch.int32)
batch 0 finished
tensor([[30, 31, 32, 33, 34],
        [40, 41, 42, 43, 44],
        [50, 51, 52, 53, 54]], dtype=torch.int32) tensor([[35],
        [45],
        [55]], dtype=torch.int32)
batch 1 finished
tensor([[60, 61, 62, 63, 64],
        [70, 71, 72, 73, 74],
        [80, 81, 82, 83, 84]], dtype=torch.int32) tensor([[65],
        [75],
        [85]], dtype=torch.int32)
batch 2 finished
tensor([[ 90,  91,  92,  93,  94],
        [100, 101, 102, 103, 104],
        [110, 111, 112, 113, 114]], dtype=torch.int32) tensor([[ 95],
        [105],
        [115]], dtype=torch.int32)
batch 3 finished
tensor([[120, 121, 122, 123, 124],
        [130, 131, 132, 133, 134],
        [140, 141, 142, 143, 144]], dtype=torch.int32) tensor([[125],
        [135],
        [145]], dtype=torch.int32)
batch 4 finished
tensor([[150, 151, 

* Reference

 -. https://www.youtube.com/watch?v=zN49HdDxHi8&list=PLlMkM4tgfjnJ3I-dbhO9JTw7gNty6o_2m&index=8